project:
  type: website
  render:
  - "01*.qmd"
  - "*.qmd"
  - "!archived/"
  - "!99*"

website:
  title: "MLS Salaries"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"

format:
  html:
    theme: cosmo
    toc: true
    df-print: paged
    code-overflow: wrap


