---
title: "API explore"
---

Here I'm trying out different API products to use with MLS Salaries

```{r}
#| label: setup
#| echo: true
#| results: hide
#| message: false
#| warning: false

library(tidyverse)
library(janitor)
library(usfootballR)
library(teamcolors)
library(scales)
```


## Import

### Getting our data

```{r}
salaries <- read_rds("data-processed/mls-salaries.rds")

salaries |> glimpse()
```

I need to make some data to use

```{r}
sal_team <- salaries |> 
  group_by(year, club_long) |> 
  summarise(total_compensation = sum(compensation)) |> 
  arrange(total_compensation |> desc())

sal_team_rank <- salaries |> 
  filter(club_short != "MLS" | club_short |> is.na()) |> 
  group_by(year, club_short, club_long) |> 
  summarise(
    total_comp = sum(compensation, na.rm = TRUE)
  ) |> 
  arrange(year, total_comp |> desc()) |> 
  ungroup() |>
  mutate(rank = rank(-total_comp), .by = year)

sal_team_rank_top <- sal_team_rank |> 
  filter(rank <= 5,
         year >= "2019")


```




## usfootballr

Here I try to use the colors from the usfootballr package and apply them to a chart.

```{r}
espn_teams <- espn_mls_teams()

sal_top_2023 <- sal_team_rank_top |> left_join(espn_teams, join_by(club_short == abbreviation)) |> 
  select(1:4, 11:12) |> 
  filter(year == "2023")

sal_top_2023_col <- sal_top_2023 |> 
  mutate(color = paste("#", color, sep = ""),
         alternate_color = paste("#", alternate_color, sep = "")
        )

sal_top_2023_col
```

Now to plot with the color?

```{r}
sal_top_2023_col |> 
  ggplot(aes(x = club_short, y = total_comp)) +
  geom_col(fill = sal_top_2023_col$alternate_color) +
  scale_y_continuous(labels = label_dollar(scale = .00001, accuracy = 2)) +
  geom_text(aes(
    label = dollar(total_comp, scale = .00001, accuracy = 2, digits = 3)),
    color = "white", vjust = 1.5
  ) +
  labs(
    title = "Top five spending teams 2023",
    y = "Total spending in $ millions"
  )

```

### From teamcolors

We'll try this, but from older data because they won't have some teams.

```{r}

mls_colors <- teamcolors |> filter(league == "mls") |> 
  select(1, 3:4)

mls_colors_udpated <- mls_colors |> 
  mutate(club_long = recode(
    name,
    "Chicago Fire" = "Chicago Fire FC"
  )) |> select(-name)

mls_colors_udpated


sal_team_2019 <- sal_team |> filter(year == 2019) |>
  left_join(mls_colors_udpated, join_by(club_long)) |> 
  drop_na(primary)

sal_team_2019
```

```{r}
#| label: fig-colors-teamcolors
#| fig-height: 7

sal_team_2019 |> 
  drop_na(primary) |> 
  ggplot(aes(y = club_long |> reorder(total_compensation), x = total_compensation)) +
  geom_col(fill = sal_team_2019$primary) +
  scale_x_continuous(labels = label_dollar(scale = .00001, accuracy = 2)) +
  geom_text(aes(
    label = dollar(total_compensation, scale = .00001, accuracy = 2, digits = 3)),
    color = "white", hjust = 1.25
  ) +
  labs(
    title = "Totally incomplete list of 2019 salaries",
    subtitle = "Only includes clubs with color values in \"teamcolors\" package.",
    y = "",
    x = "Team spending in $ millions"
  )

```


